"""Initial migration

Revision ID: 11f873a6a9ed
Revises: 
Create Date: 2024-09-28 18:52:40.079382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11f873a6a9ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_table')
    op.drop_table('items')
    op.drop_table('assessment_item')
    op.drop_table('roles')
    op.drop_table('assessments')
    op.drop_table('assessment_table')
    op.drop_table('assessment_item_associationtable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_item_associationtable',
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_table.id'], name='assessment_item_associationtable_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['item_table.id'], name='assessment_item_associationtable_item_id_fkey'),
    sa.PrimaryKeyConstraint('assessment_id', 'item_id', name='assessment_item_associationtable_pkey')
    )
    op.create_table('assessment_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='assessment_table_pkey'),
    sa.UniqueConstraint('name', name='assessment_table_name_key')
    )
    op.create_table('assessments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('assessments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='assessments_pkey'),
    sa.UniqueConstraint('name', name='assessments_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    op.create_table('assessment_item',
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_item_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='assessment_item_item_id_fkey'),
    sa.PrimaryKeyConstraint('assessment_id', 'item_id', name='assessment_item_pkey')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_type', postgresql.ENUM('OPENQUESTION', 'SECTION', 'THEMEDMODULE', name='itemtype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_table('item_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_type', postgresql.ENUM('OPENQUESTION', 'SECTION', 'THEMEDMODULE', name='itemtype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_table_pkey')
    )
    # ### end Alembic commands ###
